### Health check
GET http://127.0.0.1:8000/health

###

### Create lead
POST http://127.0.0.1:8000/api/v1/leads
Content-Type: application/json

{
  "name": "Budi Santoso",
  "phone": "08123456789",
  "source": "facebook",
  "interest": "Land in Jogja"
}

###

### Get all leads
GET http://127.0.0.1:8000/api/v1/leads
